### ISSUE TITLE
[Documentation] Update Contributing.md to mention ChangeLog

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6311]
`Contributing.md` file should be updated include a mention like `For feature changes that would be included in the Release notes, be sure to modify the ChangeLog.md file`
--? if we are still doing this for 23 release

**Comment by johnsaigle** [comment]
We're for sure using it. Last updated 5 days ago.https://github.com/aces/Loris/blob/master/CHANGELOG.md#loris-230-release-date-

**Comment by christinerogers** [comment]
Today's LORIS meeting: @ridz1208 clarified what code changes should go in the Changelog-
* Any non-insignificant change goes in.  (many PRs currently need remedial Changelog entries)
* Bug fixes iff they apply to a prior release, but not bugs introduced+fixed in same release.

We may eventually have another logging file for “Notes for Existing Projects”, but not yet.

**Comment by johnsaigle** [comment]
I think CHANGELOG is a superset of whatever would go into 'Add To Release Notes' and 'Notes For Existing Projects'. If anything is important enough that it would be included in those, it should also be in the CHANGELOG.

I see the changelog as being a bulleted record of notable changes to the code. It can also serve as an outline when drafting the official release notes. It wouldn't, for example, contain instructions on how to migrate a database or how to run a script, but it would contain a record that those things have been changed.

**Comment by ridz1208** [comment]
@johnsaigle I agree with your statement. I think we should still have somewhere else to build migration instructions as well but I'll leave that for another issue/PR.

will you be adding the Changelog note to the contributing document ?

**Comment by johnsaigle** [comment]
I think it could be better as a quick GSOC ticket. I'm happy to leave it as an entry-level task for the time being.

**Comment by christinerogers** [comment]
@laemtl how about taking a crack at this for the `23.0-release` branch?
