### ISSUE TITLE
[my_preferences] - Notification missing for media module

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8553]
**Describe the bug**
A clear and concise description of what the bug is

Despite having permissions for the media module, I cannot select to be notified for new upload or downloads.
**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
<img width="1737" alt="image" src="https://user-images.githubusercontent.com/25854264/230128217-a2a2490e-0aee-45a9-ac1b-e4735f7ad3ff.png">
<img width="846" alt="image" src="https://user-images.githubusercontent.com/25854264/230128310-a5987113-8622-44f7-9366-d589549d93c9.png">

**What did you expect to happen?**
I should be able to select receiving notifications for this module.

**Comment by xlecours** [comment]
@kongtiaowang Can you enable this config in the database?

**Comment by kongtiaowang** [comment]
@xlecours Ok, it has been enabled.

**Comment by xlecours** [comment]
@charliehenrib Can you try to test again?

**Comment by charliehenrib** [comment]
@xlecours this is what I see under my preferences despite having access to the media module - It seems like the notification system for media is still missing: 
![image](https://user-images.githubusercontent.com/25854264/233641617-99892b56-b62c-4a05-8dab-8fa4e8be5f54.png)

**Comment by xlecours** [comment]
@kongtiaowang Can you check the database if the notification* tables have the correct ids ? Thanks you

**Comment by kongtiaowang** [comment]
@kongtiaowang @charliehenrib It has been fixed on testing VM. Could you test it again? I will send a PR to fix the RB_notification_modules_services_rel data.

**Comment by charliehenrib** [comment]
@kongtiaowang @xlecours Tested and it is working now. I also tested receiving the notification and all is working. 

Thank you

**Comment by xlecours** [comment]
database state issue.

**Comment by SantiagoTG** [comment]
Still an issue when testing on COPN.

<img width="1383" alt="Screenshot 2023-06-08 at 11 04 31 AM" src="https://github.com/aces/Loris/assets/54332302/eec58c77-c4d9-485a-b018-6075aaddb57a">
